"""Package-owned SFT task generators."""

from chess_llm.sft.generators.base import TaskGenerator
from chess_llm.sft.generators.tier1_perception import (
    BoardToFEN,
    FENAssembly,
    FENBoardEdit,
    FENRankCellEdit,
    FENRankExpansion,
    FENRowApplication,
    FENToBoard,
    MaterialBalanceTrace,
    MaterialInventory,
    MaterialPieceCounts,
    MaterialValueTotals,
    MoveSquareEdits,
    MultiMoveStateTracking,
    PieceCounting,
    PieceIdentification,
    RankLookup,
    SquareCoordinates,
    SquareLookup,
    StateTracking,
)
from chess_llm.sft.generators.tier2_rules import (
    CheckDetection,
    KingSafetyFilter,
    LegalFilterTrace,
    LegalMoveGen,
    LegalMovesByPiece,
    MoveLegalityCheck,
    PieceLegalFilter,
    PiecePseudoLegalMoves,
    PieceSpecificMoves,
    RayWalk,
    SidePieceInventory,
    SpecialRules,
)
from chess_llm.sft.generators.tier3_tactics import (
    AttackedDefended,
    AvailableCaptures,
    HangingPieceClaimVerification,
    HangingPieceFilter,
    HangingPieceStatus,
    HangingPieces,
    TacticalPatterns,
    Threats,
)
from chess_llm.sft.generators.tier4_evaluation import (
    MaterialBalance,
    PawnStructure,
    PositionEvaluation,
)
from chess_llm.sft.generators.tier5_openings import (
    OpeningContinuation,
    OpeningIdentification,
    OpeningPrinciples,
)
from chess_llm.sft.generators.tier6_endgames import (
    EndgameBestMove,
    EndgameClassification,
    EndgamePrinciples,
    EndgameWDL,
)
from chess_llm.sft.generators.tier7_planning import (
    BestLineTrace,
    BestMoveSelection,
    CandidateRatings,
    MoveConsequence,
    PuzzleSolving,
)
from chess_llm.sft.generators.tier7_verification import StepVerification

TIER_GENERATORS: dict[int, list[type[TaskGenerator]]] = {
    1: [
        FENToBoard,
        BoardToFEN,
        PieceIdentification,
        PieceCounting,
        SquareLookup,
        RankLookup,
        SquareCoordinates,
        FENRankExpansion,
        FENRankCellEdit,
        FENBoardEdit,
        MaterialInventory,
        MaterialPieceCounts,
        MaterialValueTotals,
        MaterialBalanceTrace,
        MoveSquareEdits,
        FENRowApplication,
        FENAssembly,
        StateTracking,
        MultiMoveStateTracking,
    ],
    2: [
        SidePieceInventory,
        LegalMoveGen,
        PieceSpecificMoves,
        PiecePseudoLegalMoves,
        PieceLegalFilter,
        KingSafetyFilter,
        LegalMovesByPiece,
        RayWalk,
        LegalFilterTrace,
        MoveLegalityCheck,
        CheckDetection,
        SpecialRules,
    ],
    3: [
        AvailableCaptures,
        Threats,
        AttackedDefended,
        TacticalPatterns,
        HangingPieces,
        HangingPieceStatus,
        HangingPieceFilter,
        HangingPieceClaimVerification,
    ],
    4: [MaterialBalance, PositionEvaluation, PawnStructure],
    5: [OpeningIdentification, OpeningContinuation, OpeningPrinciples],
    6: [EndgameClassification, EndgameWDL, EndgameBestMove, EndgamePrinciples],
    7: [
        BestMoveSelection,
        PuzzleSolving,
        MoveConsequence,
        CandidateRatings,
        BestLineTrace,
        StepVerification,
    ],
}

__all__ = [
    "AttackedDefended",
    "AvailableCaptures",
    "BestLineTrace",
    "BestMoveSelection",
    "BoardToFEN",
    "CandidateRatings",
    "CheckDetection",
    "EndgameBestMove",
    "EndgameClassification",
    "EndgamePrinciples",
    "EndgameWDL",
    "FENAssembly",
    "FENBoardEdit",
    "FENRankCellEdit",
    "FENRankExpansion",
    "FENRowApplication",
    "FENToBoard",
    "HangingPieceFilter",
    "HangingPieceClaimVerification",
    "HangingPieceStatus",
    "HangingPieces",
    "KingSafetyFilter",
    "LegalFilterTrace",
    "LegalMoveGen",
    "LegalMovesByPiece",
    "MaterialBalanceTrace",
    "MaterialBalance",
    "MaterialInventory",
    "MaterialPieceCounts",
    "MaterialValueTotals",
    "MoveSquareEdits",
    "MoveConsequence",
    "MoveLegalityCheck",
    "MultiMoveStateTracking",
    "OpeningContinuation",
    "OpeningIdentification",
    "OpeningPrinciples",
    "PawnStructure",
    "PieceCounting",
    "PieceIdentification",
    "PieceLegalFilter",
    "PiecePseudoLegalMoves",
    "PieceSpecificMoves",
    "PositionEvaluation",
    "PuzzleSolving",
    "RankLookup",
    "RayWalk",
    "SquareCoordinates",
    "SquareLookup",
    "SidePieceInventory",
    "SpecialRules",
    "StateTracking",
    "StepVerification",
    "TIER_GENERATORS",
    "TacticalPatterns",
    "TaskGenerator",
    "Threats",
]
